name: "release"

db:
  default:
    dsn: "root:123456@tcp(0.0.0.0:3306)/test?charset=utf8mb4"
    max_open_conn: 100 #打开连接的最大数量，默认100
    max_idle_conn: 10 #空闲连接的最大数量，默认10
    max_idle_time: 600 #空闲连接的最大存活时间，单位秒，默认600
    log_level: 4 #Silent 1、Error 2、Warn 3、Info 4，默认3
    slow_threshold: 1 #慢SQL阈值，单位秒，默认1
  postgres:
    driver: "postgres" #驱动，mysql、postgres、sqlite、sqlserver、clickhouse，默认mysql
    dsn: "host=localhost user=postgres password= dbname=test port=5432"
    max_open_conn: 100 #打开连接的最大数量，默认100
    max_idle_conn: 10 #空闲连接的最大数量，默认10
    max_idle_time: 600 #空闲连接的最大存活时间，单位秒，默认600
    log_level: 4 #Silent 1、Error 2、Warn 3、Info 4，默认3
    slow_threshold: 1 #慢SQL阈值，单位秒，默认1

redis:
  default:
    address:
      - "0.0.0.0:6379"
    password: "" #密码，默认空
    db: 0
    pool_size: 100 #连接池最大数量，默认100
    tls: false #是否启用TLS，默认不启用
    min_idle_conns: 10 #最小空闲连接数，默认0
    max_idle_conns: 100 #最大空闲连接数，默认0（无限制）
    conn_max_idle_time: 600 #连接最大空闲时间，单位秒，默认30分钟
  cluster:
    address:
      - "0.0.0.0:6379"
      - "0.0.0.0:6380"
    password: "" #密码，默认空
    pool_size: 100 #连接池最大数量，默认100
    tls: false #是否启用TLS，默认不启用
    min_idle_conns: 10 #最小空闲连接数，默认0
    max_idle_conns: 100 #最大空闲连接数，默认0（无限制）
    conn_max_idle_time: 600 #连接最大空闲时间，单位秒，默认30分钟
